namespace Hack.io.GX;

public enum GXFogType : byte
{
    NONE = 0x00,

    PERSPECTIVE_LINEAR = 0x02,
    PERSPECTIVE_EXP = 0x04,
    PERSPECTIVE_EXP2 = 0x05,
    PERSPECTIVE_REVEXP = 0x06,
    PERSPECTIVE_REVEXP2 = 0x07,

    ORTHOGRAPHIC_LINEAR = 0x0A,
    ORTHOGRAPHIC_EXP = 0x0C,
    ORTHOGRAPHIC_EXP2 = 0x0D,
    ORTHOGRAPHIC_REVEXP = 0x0E,
    ORTHOGRAPHIC_REVEXP2 = 0x0F,
};