namespace Hack.io.GX;

public enum GXTexGenMatrix : byte
{
    TEXGENMTX_IDENTITY = 60,
    TEXGENMTX_TEXTUREMATRIX0 = 30,
    TEXGENMTX_TEXTUREMATRIX1 = 33,
    TEXGENMTX_TEXTUREMATRIX2 = 36,
    TEXGENMTX_TEXTUREMATRIX3 = 39,
    TEXGENMTX_TEXTUREMATRIX4 = 42,
    TEXGENMTX_TEXTUREMATRIX5 = 45,
    TEXGENMTX_TEXTUREMATRIX6 = 48,
    TEXGENMTX_TEXTUREMATRIX7 = 51,
    TEXGENMTX_TEXTUREMATRIX8 = 54,
    TEXGENMTX_TEXTUREMATRIX9 = 57,

    /* Clever games can use PNMTX as inputs to texgen. */
    TEXGENMTX_PNMTX0 = 0,
    TEXGENMTX_PNMTX1 = 3,
    TEXGENMTX_PNMTX2 = 6,
    TEXGENMTX_PNMTX3 = 9,
    TEXGENMTX_PNMTX4 = 12,
    TEXGENMTX_PNMTX5 = 15,
    TEXGENMTX_PNMTX6 = 18,
    TEXGENMTX_PNMTX7 = 21,
    TEXGENMTX_PNMTX8 = 24,
    TEXGENMTX_PNMTX9 = 27,
};