namespace Hack.io.GX;

public enum GXTexGenSrc : byte
{
    TEXGENSRC_POSITION = 0,
    TEXGENSRC_NORMAL = 1,
    TEXGENSRC_BINORMAL = 2,
    TEXGENSRC_TANGENT = 3,
    TEXGENSRC_TEXTURE0 = 4,
    TEXGENSRC_TEXTURE1 = 5,
    TEXGENSRC_TEXTURE2 = 6,
    TEXGENSRC_TEXTURE3 = 7,
    TEXGENSRC_TEXTURE4 = 8,
    TEXGENSRC_TEXTURE5 = 9,
    TEXGENSRC_TEXTURE6 = 10,
    TEXGENSRC_TEXTURE7 = 11,
    TEXGENSRC_TEXCOORD0 = 12,
    TEXGENSRC_TEXCOORD1 = 13,
    TEXGENSRC_TEXCOORD2 = 14,
    TEXGENSRC_TEXCOORD3 = 15,
    TEXGENSRC_TEXCOORD4 = 16,
    TEXGENSRC_TEXCOORD5 = 17,
    TEXGENSRC_TEXCOORD6 = 18,
    TEXGENSRC_COLOR0 = 19,
    TEXGENSRC_COLOR1 = 20,
};